/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/app`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/pages/premium/premium`; params?: Router.UnknownInputParams; } | { pathname: `/pages/chat/chat`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/BottomBar`; params?: Router.UnknownInputParams; } | { pathname: `/pages/forgot-password/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/pages/home/home`; params?: Router.UnknownInputParams; } | { pathname: `/pages/login/login`; params?: Router.UnknownInputParams; } | { pathname: `/pages/login-user/login-user`; params?: Router.UnknownInputParams; } | { pathname: `/pages/notifications/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/pages/payment/payment`; params?: Router.UnknownInputParams; } | { pathname: `/pages/profile/profile`; params?: Router.UnknownInputParams; } | { pathname: `/pages/register/register`; params?: Router.UnknownInputParams; } | { pathname: `/pages/roles/role`; params?: Router.UnknownInputParams; } | { pathname: `/pages/search/search`; params?: Router.UnknownInputParams; } | { pathname: `/pages/verify-code/verify-code`; params?: Router.UnknownInputParams; } | { pathname: `/utils/scaling`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/app`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/premium/premium`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/chat/chat`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/BottomBar`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/forgot-password/forgot-password`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/home/home`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/login/login`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/login-user/login-user`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/notifications/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/payment/payment`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/profile/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/register/register`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/roles/role`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/search/search`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/verify-code/verify-code`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/scaling`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/app${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/pages/premium/premium${`?${string}` | `#${string}` | ''}` | `/pages/chat/chat${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/BottomBar${`?${string}` | `#${string}` | ''}` | `/pages/forgot-password/forgot-password${`?${string}` | `#${string}` | ''}` | `/pages/home/home${`?${string}` | `#${string}` | ''}` | `/pages/login/login${`?${string}` | `#${string}` | ''}` | `/pages/login-user/login-user${`?${string}` | `#${string}` | ''}` | `/pages/notifications/notifications${`?${string}` | `#${string}` | ''}` | `/pages/payment/payment${`?${string}` | `#${string}` | ''}` | `/pages/profile/profile${`?${string}` | `#${string}` | ''}` | `/pages/register/register${`?${string}` | `#${string}` | ''}` | `/pages/roles/role${`?${string}` | `#${string}` | ''}` | `/pages/search/search${`?${string}` | `#${string}` | ''}` | `/pages/verify-code/verify-code${`?${string}` | `#${string}` | ''}` | `/utils/scaling${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/app`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/pages/premium/premium`; params?: Router.UnknownInputParams; } | { pathname: `/pages/chat/chat`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/BottomBar`; params?: Router.UnknownInputParams; } | { pathname: `/pages/forgot-password/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/pages/home/home`; params?: Router.UnknownInputParams; } | { pathname: `/pages/login/login`; params?: Router.UnknownInputParams; } | { pathname: `/pages/login-user/login-user`; params?: Router.UnknownInputParams; } | { pathname: `/pages/notifications/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/pages/payment/payment`; params?: Router.UnknownInputParams; } | { pathname: `/pages/profile/profile`; params?: Router.UnknownInputParams; } | { pathname: `/pages/register/register`; params?: Router.UnknownInputParams; } | { pathname: `/pages/roles/role`; params?: Router.UnknownInputParams; } | { pathname: `/pages/search/search`; params?: Router.UnknownInputParams; } | { pathname: `/pages/verify-code/verify-code`; params?: Router.UnknownInputParams; } | { pathname: `/utils/scaling`; params?: Router.UnknownInputParams; };
    }
  }
}
